### ISSUE TITLE
Random Claiming Route bug, stuck on player's turn

### ISSUE THREAD

**Issue by jakegriffey** [byucs340ta/Fall2018#101]
Tried to claim a gray route with three purple cards, but nothing happened, and wouldn't let us
claim any other routes on that turn either.

Here is the exact error from the server:

Mon Nov 26 16:14:59 MST 2018 - (ERROR) Error executing command of type claim_route
com.team27.sharedlibrary.exceptions.OutOfTurnException
        at com.team27.sharedlibrary.models.GameTurnTracker.assertPlayersTurn(GameTurnTracker.java:114)
        at com.team27.sharedlibrary.models.ActiveGame.claimRoute(ActiveGame.java:338)
        at com.team27.tickettorideserver.models.ActiveGameManager.claimRoute(ActiveGameManager.java:114)
        at com.team27.tickettorideserver.models.ServerFacade.claimRoute(ServerFacade.java:216)
        at com.team27.tickettorideserver.commands.gamecommands.ClaimRouteCommand.executeActiveGameLogic(ClaimRouteCommand.java:23)
        at com.team27.tickettorideserver.commands.gamecommands.ActiveGameCommand.execute(ActiveGameCommand.java:106)
        at com.team27.tickettorideserver.models.ServerFacade.exec(ServerFacade.java:136)
        at com.team27.tickettorideserver.http.ExecHandler.handlePost(ExecHandler.java:15)
        at com.team27.tickettorideserver.http.ExecHandler.handlePost(ExecHandler.java:7)
        at com.team27.tickettorideserver.http.HandlerBase.handle(HandlerBase.java:31)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
        at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(Unknown Source)
        at sun.net.httpserver.ServerImpl$Dispatcher.handle(Unknown Source)
        at sun.net.httpserver.ServerImpl$Dispatcher.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by drakebw** [comment]
Found race condition and closed it
