### ISSUE TITLE
Backing out of game throws error

### ISSUE THREAD

**Issue by jakegriffey** [byucs340ta/Fall2018#106]
Most likely related to unfinished AI implementation but handy to know. Doesn't really affect the game.

Here's the error the server threw:

Mon Nov 26 16:16:05 MST 2018 - (INFO) Exec of type: leave_active_game
Exception in thread "Thread-2" java.lang.NoSuchMethodError: com.team27.sharedlibrary.models.Player.<init>(Lcom/team27/sharedlibrary/models/Player;)V
        at com.team27.tickettorideserver.ai.players.BaseAIPlayer.<init>(BaseAIPlayer.java:30)
        at com.team27.tickettorideserver.ai.players.DumbTrainCardDrawingPlayer.<init>(DumbTrainCardDrawingPlayer.java:31)
        at com.team27.tickettorideserver.commands.gamecommands.LeaveActiveGameCommand.executeActiveGameLogic(LeaveActiveGameCommand.java:25)
        at com.team27.tickettorideserver.commands.gamecommands.ActiveGameCommand.execute(ActiveGameCommand.java:106)
        at com.team27.tickettorideserver.models.ServerFacade.exec(ServerFacade.java:136)
        at com.team27.tickettorideserver.http.ExecHandler.handlePost(ExecHandler.java:15)
        at com.team27.tickettorideserver.http.ExecHandler.handlePost(ExecHandler.java:7)
        at com.team27.tickettorideserver.http.HandlerBase.handle(HandlerBase.java:31)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
        at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(Unknown Source)
        at sun.net.httpserver.ServerImpl$Dispatcher.handle(Unknown Source)
        at sun.net.httpserver.ServerImpl$Dispatcher.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by webMan1** [comment]
This is our bad. In our second ZIP file we didn't redeploy the first SharedLibrary.jar with the second one. The Player.class lives in the shared library and the DumbTrainCardDrawingPlayer.class lives in the server jar. So, there were two Player classes living in our application, P1, compiled at time 1 and P2, compiled at time 2. It was unable to case a DumbTrainCardPlayer (inheriting from P2) to P1 for the class constructor constructor of P1.

This is the only explanation for what happened given that this method is checked for at compile time.

https://stackoverflow.com/questions/33832400/java-lang-nosuchmethoderror-related-with-a-class-constructor
