### ISSUE TITLE
game end doesn't work view dpesm

### ISSUE THREAD

**Issue by rmfirth** [byucs340ta/Fall2018#95]

**Comment by rmfirth** [comment]
Here is that stack trace for yadawg:


java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at ttr.shared.command.Command.execute(Command.java:70)
	at ttr.server.facade.ServerCommandManager.executeCommands(ServerCommandManager.java:18)
	at ttr.server.handlers.ExecuteCommandHandler.processString(ExecuteCommandHandler.java:62)
	at ttr.server.handlers.ExecuteCommandHandler.handle(ExecuteCommandHandler.java:35)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:691)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:663)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:159)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:444)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:409)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NullPointerException
	at ttr.shared.model.Game.calculateGameOverScores(Game.java:408)
	at ttr.shared.model.Game.getGameOverScoreTable(Game.java:387)
	at ttr.server.facade.ServerFacade.updateTurn(ServerFacade.java:563)
	at ttr.server.facade.ServerFacade.claimRoute(ServerFacade.java:454)
	... 17 more
java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at ttr.shared.command.Command.execute(Command.java:70)
	at ttr.server.facade.ServerCommandManager.executeCommands(ServerCommandManager.java:18)
	at ttr.server.handlers.ExecuteCommandHandler.processString(ExecuteCommandHandler.java:62)
	at ttr.server.handlers.ExecuteCommandHandler.handle(ExecuteCommandHandler.java:35)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:691)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:663)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:159)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:444)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:409)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NullPointerException
	at ttr.shared.model.Game.calculateGameOverScores(Game.java:408)
	at ttr.shared.model.Game.getGameOverScoreTable(Game.java:387)
	at ttr.server.facade.ServerFacade.updateTurn(ServerFacade.java:563)
	at ttr.server.facade.ServerFacade.claimRoute(ServerFacade.java:454)
	... 17 more

**Comment by a7ger** [comment]
Null pointer exception has been prevented!
